on:
  push:
    branches:
      - main
      - developing


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust the version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Correctly upgrade pip
        pip install pytest pytest-cov  # Install pytest and coverage dependencies

    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml

    - uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          

    - name: Download Sonar Scanner #will not work
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux.zip
        # Move into the extracted directory
        cd sonar-scanner-6.2.1.4610-linux/bin



    - name: SonarQube practice
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        ./sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.python.coverage.reportPaths=coverage.xml \
          -Dsonar.exclusions=test_main.py \  # Exclude test files from analysis
